### ISSUE TITLE
Points values for British peninsular war artillery

### ISSUE THREAD

**Issue by wadtech** [BSData/sharp-practice#1]
It should be 6/7/9 points for light/medium/heavy gun.

I'm seeing 0/1/2 points in the list.

![IMG_20190822_205754](https://user-images.githubusercontent.com/1141692/63545536-8f478d80-c51f-11e9-86d0-1890fc802a8e.jpg)

Thanks!

**Comment by mugginns-zz** [comment]
Thank you! Fixed

**Comment by wadtech** [comment]
Thanks very much.
